#ifndef MEMORY_MAP
#define MEMORY_MAP
//bootloader
#define BOOTLOAD_SECTOR 0x07c0
#define BOOTLOADER_STACK_TOP 0x7DFF
//kernel boot
#define KERNELLOADER_SEGMENT 0x1000
#define KERNELLOADER_MEM_BASE 0x10000
#define KERNELLOADER_SIZE 0x8000
#define KERNELLOADER_SECTOR_COUNT 0x40 
#define KERNELLOADER_STACK_TOP  0x20000
#define KERNELLOADER_OFFSET 0x0

#endif 